#!/bin/bash
# Copyright (C) 2017 AT&T Intellectual Property. All rights reserved. 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this code except in compliance
# with the License. You may obtain a copy of the License
# at http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software  
# distributed under the License is distributed on an "AS IS" BASIS,  
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or  
# implied. See the License for the specific language governing  
# permissions and limitations under the License. 

echo "================ $0 ================"
id
set -x

die()
{
    echo "$@" 1>&2
    echo $0: "$@"
    umask 022
    echo $0: "$@" >> /tmp/pgaas-failures
    exit 1
}

export CDFCFG=${INSTALL_ROOT}/opt/app/cdf/lib/cdf.cfg
export PGAASCFG=${INSTALL_ROOT}/opt/app/pgaas/lib/pgaas.cfg

if [ -d /opt/app/postgresql-9.5.2 ]
then PGDIR=/opt/app/postgresql-9.5.2
elif [ -d /usr/lib/postgresql/9.6 ]
then PGDIR=/usr/lib/postgresql/9.6
elif [ -d /usr/lib/postgresql/9.5 ]
then PGDIR=/usr/lib/postgresql/9.5
else die PostgreSQL bin directory not found
fi
CFGDIR=/opt/app/pgaas
CONF=$CFGDIR/main/postgresql.conf
if [ ! -f $CONF ]
then echo "$0: Cannot find PostgreSQL configuration" 1>&2; exit 1
fi


(
    grep '^postgres.x' < $CDFCFG | sed -e 's/^postgres/dcae_admin_db_password/' 
    echo "db_configuration=$CONF"
    echo "pg_bin_directory=$PGDIR/bin"
    echo "skip_configuration_file=$CFGDIR/lib/ignore-database-reconfiguration"
) >> $PGAASCFG
