#!/bin/bash
# Copyright (C) 2017 AT&T Intellectual Property. All rights reserved. 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this code except in compliance
# with the License. You may obtain a copy of the License
# at http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software  
# distributed under the License is distributed on an "AS IS" BASIS,  
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or  
# implied. See the License for the specific language governing  
# permissions and limitations under the License. 


# create ~postgres/.pgpass
postgrespswd=$( ${INSTALL_ROOT}/opt/app/cdf/bin/getpropvalue -x -n postgres )
repmgrpswd=$( ${INSTALL_ROOT}/opt/app/cdf/bin/getpropvalue -x -n repmgr )
umask 077
pswdfile=~postgres/.pgpass
if [ -f $pswdfile ]
then
    sed -i -e '/:postgres:/d'  -e '/:repmgr:/d' $pswdfile
fi

echo "*:*:*:postgres:$postgrespswd" >> $pswdfile
echo "*:*:*:repmgr:$repmgrpswd" >> $pswdfile
chmod 600 $pswdfile
